name: Close PullRequest
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  delete_app_variant:
    uses: sheason2019/canarails_doc/.github/workflows/mutate-app-variant.yaml@master
    secrets:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    with:
      method: DELETE
      branchName: ${{ github.head_ref }}
